### ISSUE TITLE
IMG not present

### ISSUE THREAD

**Issue by bhollan** [learn-co-curriculum/hs-issue-bot-9000#1]
I'm not sure if it's intentional, but you might want to reconsider having an unavailable image in a beginner lab.

[http://38.media.tumblr.com/70ace162d8f0654f3239aa7447a21870/tumblr_muvabkXjsz1qz6h81o1_1280.jpg](http://38.media.tumblr.com/70ace162d8f0654f3239aa7447a21870/tumblr_muvabkXjsz1qz6h81o1_1280.jpg)

in a browser yields:

```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>400EFF93F2911751</RequestId>
<HostId>
+x9K4f82Ak2R3sB9xb0PK/c5e0FPy9ZYmfhoJBEkIw/jeTT6zzNixS8wrbv6Ot4lPLZx6o+NDwU=
</HostId>
</Error>
```

Also, I don't know your release cycle, but the current version of this lab that came to me is not the version that's here.  I got no cute robot.  >:O

**Comment by AnnJohn** [comment]
assigning this one to you @jongrover

**Comment by jongrover** [comment]
The purpose of this lab is to find errors in the code. The image link is simply missing the protocol *_http:// *_ this was intentionally left out to break the link as part of the assignment.

**Comment by bhollan** [comment]
ok.  I assumed that all the images should point to images even after everything's fixed.  When I add `http://`, it gives the result quoted above. [Link](http://38.media.tumblr.com/70ace162d8f0654f3239aa7447a21870/tumblr_muvabkXjsz1qz6h81o1_1280.jpg)  If you can see something at that address, then it must be my DNS cache or something goofy about being in Mexico.
